export const ADMIN = 'ADMIN'

export const ADD_CLASSES = 'ADD_CLASSES'

export const SHOW_MODAL_ADD_CLASSES = 'SHOW_MODAL_ADD_CLASSES';
export const CLOSE_MODAL_ADD_CLASSES = 'CLOSE_MODAL_ADD_CLASSES';

export const ADD_KEY_CONTROL_CLASS_LIST = 'ADD_KEY_CONTROL_CLASS_LIST';

export const ADD_KEY_FILTER = 'ADD_KEY_FILTER'